#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Jul 06 04:56:48 MSK 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=12
shaderPack=photon_v1.3b.zip
enableShaders=false
